name: Download and Merge Videos

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  download-videos:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Sets up Python environment
        with:
          python-version: '3.12'  # Replace with your Python version (e.g., 3.8)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp  # Install yt-dlp library

      - name: Run Python script
        run: python run.py  # Replace with your actual script filename
